export const USER_REQUEST = "USER_REQUEST";
export const USER_REQUEST_SUCCESS = "USER_REQUEST_SUCCESS";
export const USER_REQUEST_ERROR = "USER_REQUEST_ERROR";
export const USER_REQUEST_RESET = "USER_REQUEST_RESET";